export enum OsComponentEnum {
    Button = 'button',
    Checkbox = 'checkbox',
    DragAndDrop = 'drag-and-drop',
    EmailBox = 'email-box',
    FieldRow = 'field-row',
    GroupBox = 'group-box',
    List = 'list',
    NumberBox = 'number-box',
    PasswordBox = 'password-box',
    RadioButton = 'radio-button',
    Resizer = 'resizer',
    ScrollView = 'scroll-view',
    Selectbox = 'selectbox',
    Slider = 'slider',
    TabGroup = 'tab-group',
    Text = 'text',
    TextBox = 'text-box',
    TextareaBox = 'textarea-box',
    TreeView = 'tree-view',
    Window = 'window',
    Grid = 'grid',
    Theme = 'theme'
}
