import { NgModule } from '@angular/core';
import { SharedModule } from '@Doc/demo-shared.module';
import {
    ButtonCounterComponent,
    ButtonOverviewComponent,
    CheckboxOverviewComponent,
    DraggerOverviewComponent,
    EmailBoxOverviewComponent,
    FormFieldOverviewComponent,
    GridOverviewComponent,
    GroupBoxOverviewComponent,
    ListOverviewComponent,
    NumberBoxOverviewComponent,
    PasswordBoxOverviewComponent,
    RadioButtonOverviewComponent,
    ResizerOverviewComponent,
    ScrollViewOverviewComponent,
    SelectboxOverviewComponent,
    SliderOverviewComponent,
    TabGroupOverviewComponent,
    TextareaOverviewComponent,
    TextBoxOverviewComponent,
    TextOverviewComponent,
    ThemeOverviewComponent,
    TreeViewOverviewComponent,
    WindowDynamicOpeningComponent,
    WindowOverviewComponent,
    WindowTitleBarComponent
} from './examples';

@NgModule({
    declarations: [
        ButtonCounterComponent,
        ButtonOverviewComponent,
        CheckboxOverviewComponent,
        DraggerOverviewComponent,
        EmailBoxOverviewComponent,
        FormFieldOverviewComponent,
        GridOverviewComponent,
        GroupBoxOverviewComponent,
        ListOverviewComponent,
        NumberBoxOverviewComponent,
        PasswordBoxOverviewComponent,
        RadioButtonOverviewComponent,
        ResizerOverviewComponent,
        ScrollViewOverviewComponent,
        SelectboxOverviewComponent,
        SliderOverviewComponent,
        TabGroupOverviewComponent,
        TextareaOverviewComponent,
        TextBoxOverviewComponent,
        TextOverviewComponent,
        ThemeOverviewComponent,
        TreeViewOverviewComponent,
        WindowDynamicOpeningComponent,
        WindowOverviewComponent,
        WindowTitleBarComponent
    ],
    imports: [
        SharedModule
    ],
    exports: [
        ButtonCounterComponent,
        ButtonOverviewComponent,
        CheckboxOverviewComponent,
        DraggerOverviewComponent,
        EmailBoxOverviewComponent,
        FormFieldOverviewComponent,
        GridOverviewComponent,
        GroupBoxOverviewComponent,
        ListOverviewComponent,
        NumberBoxOverviewComponent,
        PasswordBoxOverviewComponent,
        RadioButtonOverviewComponent,
        ResizerOverviewComponent,
        ScrollViewOverviewComponent,
        SelectboxOverviewComponent,
        SliderOverviewComponent,
        TabGroupOverviewComponent,
        TextareaOverviewComponent,
        TextBoxOverviewComponent,
        TextOverviewComponent,
        ThemeOverviewComponent,
        TreeViewOverviewComponent,
        WindowDynamicOpeningComponent,
        WindowOverviewComponent,
        WindowTitleBarComponent
    ]
})
export class DocumentationModule {}
