export enum OsComponentEnum {
    Button = 'button',
    Checkbox = 'checkbox',
    Divider = 'divider',
    ContextMenu = 'context-menu',
    DragAndDrop = 'drag-and-drop',
    FormField = 'form-field',
    GroupBox = 'group-box',
    Hint = 'hint',
    List = 'list',
    MenuBar = 'menu-bar',
    RadioButton = 'radio-button',
    Resizer = 'resizer',
    ScrollView = 'scroll-view',
    Selection = 'selection',
    Dropdown = 'dropdown',
    Slider = 'slider',
    TabGroup = 'tab-group',
    Text = 'text',
    Input = 'input',
    TreeView = 'tree-view',
    Window = 'window',
    Grid = 'grid',
    Theme = 'theme',
    Utils = 'utils'
}
